server:
  port: 8040
  
spring:
  application:
    name: microservice-gateway-zuul-fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true  
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
