server:
  port: 8750
  
spring:
  application:
    name: microservice-zuul-file-upload
  http:
    multipart:
      enabled: true
      max-file-size: 2000Mb
      max-request-size: 2500Mb
      
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
