server:
  port: 8731
  
spring:
  application:
    name: microservice-hystrix-turbine
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX2
  appConfig: microservice-consumer-movie-ribbon-hystrix2
turbine.instanceUrlSuffix.MICROSERVICE-CONSUMER-MOVIE-RIBBON-HYSTRIX2: /ribbon/hystrix.stream