server:
  port: 8080
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/buchuang/MicroService-Config-Server 
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
  key: foo
security:
  basic:
    enabled: true
  user: 
    name: user
    password: password123