server:
  port: 8910
  
spring:
  application:
    name: microservice-consumer-movie
    
eureka:
  client:
    healthcheck:
        enable: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    

